#!/bin/bash

# Print current git repository information as Environment variables

GIT_ENV_VARS=
GIT_ENV_VAR_PREFIX=""
GIT_ENV_VAR_SUFFIX="\n"

function append_var() {
	GIT_ENV_VARS+="${GIT_ENV_VAR_PREFIX}${@}${GIT_ENV_VAR_SUFFIX}"
}

function main() {
	if [[ "${1}" == "--oneline" ]]; then
		GIT_ENV_VAR_PREFIX=" "
		GIT_ENV_VAR_SUFFIX=""
	fi


	append_var GIT_ACTOR=$(git config --get user.email)

	# Add default behavior if current dir is not a git repo
	if [ -d ".git" ]; then
		append_var GIT_REPOSITORY=$(git remote show origin -n | grep h.URL | sed 's/.*://;s/.git$//')
		append_var GIT_REPOSITORY_OWNER=$(git remote show origin -n | grep h.URL | sed 's/.*://;s/\/.*.git$//')
		append_var GIT_REF=$(git rev-parse --symbolic-full-name HEAD)
		append_var GIT_REF_NAME=$(git rev-parse --abbrev-ref HEAD)
		append_var GIT_SHA=$(git rev-parse --verify HEAD)
	else
		append_var GIT_REPOSITORY=
		append_var GIT_REPOSITORY_OWNER=
		append_var GIT_REF=
		append_var GIT_REF_NAME=
		append_var GIT_SHA=
	fi

	echo -e ${GIT_ENV_VARS}
}

main "$@"
